# Configuration for google cloud ml with gpu and hyperparameter optimization.

trainingInput:
  region: us-west1
  scaleTier: BASIC_GPU
  pythonVersion: '3.5'
  runtimeVersion: '1.13'
  hyperparameters:
    goal: MAXIMIZE
    params:
      - parameterName: learning_rate
        type: DISCRETE
        discreteValues:
          - .0000001
          - .000001
          - .00001
          - .0001
    maxTrials: !!int 4
    maxParallelTrials: !!int 4
    hyperparameterMetricTag: accuracy
    enableTrialEarlyStopping: TRUE
    algorithm: GRID_SEARCH
