# Configuration for google cloud ml with gpu.

trainingInput:
  region: us-east1
  scaleTier: CUSTOM
  masterType: standard_p100
  pythonVersion: '3.5'
  runtimeVersion: '1.13'
#  masterType: n1-standard-4
#  workerType: n1-standard-4
#  workerCount: !!int 1
#  workerConfig:
#    acceleratorConfig:
#      count: 1
#      type: NVIDIA_TESLA_K80
#  parameterServerCount: !!int 1
#  parameterServerType: n1-standard-4
